"""Initial schema setup

Revision ID: 752aadb36230
Revises: 
Create Date: 2026-07-23 21:11:17.995087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752aadb36230'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_risk_alerts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brands',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sales_orders',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_so_date', 'sales_orders', ['order_date'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('lead_time', sa.Integer(), nullable=True),
    sa.Column('moq', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_rating', sa.String(), nullable=True),
    sa.Column('average_delay', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gst_number')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('warehouses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('warehouse_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('manager', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_utilization', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('operating_hours', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_code')
    )
    op.create_table('employees',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('warehouse_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('brand_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('supplier_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('warranty', sa.String(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('average_daily_sales', sa.Integer(), nullable=True),
    sa.Column('lead_time', sa.Integer(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('economic_order_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('idx_product_brand', 'products', ['brand_id'], unique=False)
    op.create_index('idx_product_category', 'products', ['category_id'], unique=False)
    op.create_index('idx_product_sku', 'products', ['sku'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('supplier_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('warehouse_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_po_status', 'purchase_orders', ['status'], unique=False)
    op.create_index('idx_po_supplier', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('supplier_performance',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('supplier_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('delivery_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('average_delay', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('complaint_count', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_kpi',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('warehouse_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('inbound', sa.Integer(), nullable=True),
    sa.Column('outbound', sa.Integer(), nullable=True),
    sa.Column('picking', sa.Integer(), nullable=True),
    sa.Column('packing', sa.Integer(), nullable=True),
    sa.Column('returns', sa.Integer(), nullable=True),
    sa.Column('warehouse_utilization', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('demand', sa.Integer(), nullable=False),
    sa.Column('seasonality_factor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('trend_indicator', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('forecasted_demand', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('warehouse_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('damaged_quantity', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.CheckConstraint('available_quantity >= 0', name='check_avail_positive'),
    sa.CheckConstraint('quantity_on_hand >= 0', name='check_qty_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_warehouse_product', 'inventory', ['warehouse_id', 'product_id'], unique=True)
    op.create_table('inventory_movements',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('warehouse_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('movement_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_mov_date', 'inventory_movements', ['movement_date'], unique=False)
    op.create_index('idx_inv_mov_type', 'inventory_movements', ['movement_type'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('returns',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sales_order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sales_order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.Column('current_location', sa.String(), nullable=True),
    sa.Column('dispatch_date', sa.Date(), nullable=True),
    sa.Column('expected_arrival', sa.Date(), nullable=True),
    sa.Column('actual_arrival', sa.Date(), nullable=True),
    sa.Column('delay_days', sa.Integer(), nullable=True),
    sa.Column('delay_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shipment_status', 'shipments', ['current_status'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('from_warehouse_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('to_warehouse_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_received',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('shipment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('inspection_result', sa.String(), nullable=False),
    sa.Column('accepted_quantity', sa.Integer(), nullable=False),
    sa.Column('rejected_quantity', sa.Integer(), nullable=False),
    sa.Column('quality_issue', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods_received')
    op.drop_table('stock_transfers')
    op.drop_index('idx_shipment_status', table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('sales_order_items')
    op.drop_table('returns')
    op.drop_table('purchase_order_items')
    op.drop_index('idx_inv_mov_type', table_name='inventory_movements')
    op.drop_index('idx_inv_mov_date', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('idx_inventory_warehouse_product', table_name='inventory')
    op.drop_table('inventory')
    op.drop_table('forecast_history')
    op.drop_table('demand_history')
    op.drop_table('warehouse_kpi')
    op.drop_table('supplier_performance')
    op.drop_index('idx_po_supplier', table_name='purchase_orders')
    op.drop_index('idx_po_status', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('idx_product_sku', table_name='products')
    op.drop_index('idx_product_category', table_name='products')
    op.drop_index('idx_product_brand', table_name='products')
    op.drop_table('products')
    op.drop_table('employees')
    op.drop_table('warehouses')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_index('idx_so_date', table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_table('categories')
    op.drop_table('brands')
    op.drop_table('ai_risk_alerts')
    # ### end Alembic commands ###
